site_name: hashreport
repo_name: hashreport
repo_url: https://github.com/madebyjake/hashreport
copyright: Copyright © 2025 Jake Wells

nav:
  - Overview: index.md
  - Installation: install.md
  - Usage:
    - Basic Usage: basic.md
    - Advanced Usage: advanced.md
    - Command Reference: commands.md
    - Configuration: configuration.md
    - Troubleshooting: troubleshooting.md
  - Development:
    - Contributing: contributing.md
    - Project Scripts: scripts.md

theme:
  name: material
  language: en
  font:
    text: DM Sans
    code: DM Mono
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: "black"
      accent: "teal"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: "black"
      accent: "teal"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: "black"
      accent: "teal"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - macros
  - mkdocstrings
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.progressbar
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/madebyjake/hashreport
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/hashreport/
  version:
    provider: mike
