name: 'Setup Python Environment'
description: 'Sets up Python environment with poetry and project dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python environment
      shell: bash
      run: |
        python3 -m venv $VENV_PATH
        . $VENV_PATH/bin/activate
        pip install --upgrade pip wheel setuptools poetry

    - name: Install project
      shell: bash
      run: |
        . $VENV_PATH/bin/activate
        poetry install --no-interaction

    - name: Validate metadata
      shell: bash
      run: |
        . $VENV_PATH/bin/activate
        python3 -c "from hashreport.config import get_config; print(get_config().get_metadata())"
