name: Build Packages

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      is_release: ${{ steps.check-release.outputs.is_release }}
    steps:
      - uses: actions/checkout@v4

      - id: check-release
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - id: get-version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            # Get version from Poetry for non-tag builds
            pip install poetry
            VERSION=$(poetry version -s)
            echo "version=${VERSION}" >> $GITHUB_OUTPUT
          fi

  build:
    needs: prepare
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          dnf update -y
          dnf install -y \
            git \
            python3 \
            python3-devel \
            python3-pip \
            python3-setuptools \
            python3-build \
            python3-wheel \
            python3-psutil \
            rpm-build \
            rpmdevtools \
            rpmlint

      - uses: ./.github/actions/build-package
        with:
          version: ${{ needs.prepare.outputs.version }}

      - name: Generate checksums
        run: |
          cd ~/rpmbuild/RPMS/noarch && sha256sum *.rpm > ~/SHA256SUMS
          cd ~/rpmbuild/SRPMS && sha256sum *.rpm >> ~/SHA256SUMS

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm-packages
          path: ~/rpmbuild/RPMS/noarch/*.rpm
          if-no-files-found: error

      - name: Upload source RPM
        uses: actions/upload-artifact@v4
        with:
          name: source-rpm
          path: ~/rpmbuild/SRPMS/*.rpm
          if-no-files-found: error

      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: ~/SHA256SUMS
          if-no-files-found: error

  release:
    needs: [prepare, build]
    if: needs.prepare.outputs.is_release == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: rpm-packages
          path: ./rpm-packages

      - uses: actions/download-artifact@v4
        with:
          name: source-rpm
          path: ./source-rpm

      - uses: actions/download-artifact@v4
        with:
          name: checksums
          path: ./

      - name: Generate checksums
        run: |
          cd rpm-packages && sha256sum *.rpm > ../SHA256SUMS
          cd ../source-rpm && sha256sum *.rpm >> ../SHA256SUMS

      - name: List artifacts
        run: |
          find . -type f -name "*.rpm"
          cat SHA256SUMS

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ./rpm-packages/*.rpm
            ./source-rpm/*.rpm
            ./SHA256SUMS
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
