name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  POETRY_VIRTUALENVS_CREATE: false
  POETRY_VERSION: 1.6.1

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hashreport
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # For releases, checkout the specific tag commit; for manual dispatch, use current HEAD
          ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Ensure poetry-dynamic-versioning is installed
        run: poetry self add poetry-dynamic-versioning[plugin]

      - name: Debug Git information
        run: |
          echo "Current commit: $(git rev-parse HEAD)"
          echo "Current branch: $(git branch --show-current)"
          echo "Git tags: $(git tag --list)"
          echo "Git describe: $(git describe --tags --always)"
          echo "Git status:"
          git status --porcelain

      - name: Show version
        run: poetry version

      - name: Fail if version is 0.0.0
        run: |
          VERSION=$(poetry version -s)
          if [ "$VERSION" = "0.0.0" ]; then
            echo "ERROR: Version is 0.0.0, aborting publish."
            exit 1
          fi

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
